version: 2

python:
  version: 3
  install:
    - method: pip
      path: .
    - requirements: requirements.txt
  system_packages: true
  
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: true
  
formats:
  - pdf
  - epub
